seeder:
  file: ./seeder/seeder.rb
  disabled : false

parsers:
  - file: ./parsers/listing.rb
    page_type: listing
    disabled: false

  - file: ./parsers/details.rb
    page_type: details
    disabled: false

exporters:
  - exporter_name: listing
    exporter_type: json
    collection: listings
    start_on_job_done: true
    write_mode: pretty_array

  - exporter_name: product
    exporter_type: json
    collection: products
    start_on_job_done: true
    write_mode: pretty_array

  - exporter_name: product_csv
    exporter_type: csv
    collection: products
    start_on_job_done: true
    fields:
      - header: "gid"
        path: "_gid"
      - header: "created_at"
        path: "_created_at"
      - header: "title"
        path: "title"
      - header: "price"
        path: "price"
      - header: "feedback"
        path: "feedback"
      - header: "seller"
        path: "seller"   