seeder:
  file: ./seeder/seeder.rb
  disabled : false

parsers:
  - file: ./parsers/listing.rb
    page_type: listing
    disabled: false

  - file: ./parsers/details.rb
    page_type: details
    disabled: false

exporters:
  - exporter_name: listing
    exporter_type: json
    collection: listings
    write_mode: pretty_array    